FROM haproxy:3.3.1-alpine

# Copy HAProxy configuration
COPY docker/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

# Expose port
EXPOSE 8080

# Run HAProxy
CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
